// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ9HE7LV4h8HHIOAjRL9HXRioq0Ilns50',
    appId: '1:822674575234:web:5b77155c9f757b55d2099b',
    messagingSenderId: '822674575234',
    projectId: 'minesweep-battle',
    authDomain: 'minesweep-battle.firebaseapp.com',
    storageBucket: 'minesweep-battle.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQlk5LBQFSS_5YqJelCxMJ4PO1nxu1qsE',
    appId: '1:822674575234:android:258680df65895b2dd2099b',
    messagingSenderId: '822674575234',
    projectId: 'minesweep-battle',
    storageBucket: 'minesweep-battle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC_h7zzEO_SzpUSJWYwDpO3jTJwhveU7Q',
    appId: '1:822674575234:ios:c59af39487ba12f7d2099b',
    messagingSenderId: '822674575234',
    projectId: 'minesweep-battle',
    storageBucket: 'minesweep-battle.firebasestorage.app',
    iosBundleId: 'com.minesweeper.minesweeperBattle',
  );
}
